# Pi 录像上传模式（关闭网页直播，录像保留 3 天）
# 由 start_cloud_server_linux.sh source

export LIVE_STREAM_ENABLE="${LIVE_STREAM_ENABLE:-0}"
export ELEPHANT_CLIP_RECORD_INFER="${ELEPHANT_CLIP_RECORD_INFER:-0}"
export ELEPHANT_CLIP_RETENTION_DAYS="${ELEPHANT_CLIP_RETENTION_DAYS:-3}"
export UOVISION_RETENTION_DAYS="${UOVISION_RETENTION_DAYS:-3}"
export ELEPHANT_CLIP_DIR="${ELEPHANT_CLIP_DIR:-data/clips}"
export ELEPHANT_CLIP_UPLOAD_MAX_MB="${ELEPHANT_CLIP_UPLOAD_MAX_MB:-512}"
